# Generated by Django 4.2.7 on 2023-12-26 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_nexususer_photo_de_profil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nexususer',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
