# Generated by Django 4.2.7 on 2024-01-03 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_nexususer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='nexususer',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
    ]
