# Generated by Django 4.2.7 on 2023-12-27 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0002_alter_channel_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='participants',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(),
        ),
    ]
