# Generated by Django 4.2.7 on 2023-12-27 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0003_channel_participants_alter_message_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='is_private',
            field=models.IntegerField(default=0),
        ),
    ]
